DEVX-925: Allow generic command definitions for flex workflows
fp-mt-test-org/devx-workflows pull request #1
Opened 2021-05-24 20:05 UTC by alinamchin

Allows commands to be defined in `service_config.yml` rather than having separate files per command.
Adds `flex cmd` with `list` (lists available subcommands) as well as user-specified subcommands.

2021-05-24 22:34 UTC, u2mejc commented
LGTM 👍

2021-06-01 18:41 UTC, fp-mt requested changes
This looks great!  I've got a few ideas to simplify, which we can do post-merge.

I just ran the tests locally though and they are failing, let's get those fixed before merging.  I'll sync up with @alinamchin on that.

2021-06-01 22:38 UTC, fp-mt commented on flex/cmd/list.go
> +package cmd
New list feature needs a test.

2021-06-01 23:02 UTC, alinamchin commented on flex/cmd/list.go
> +package cmd
done!

2021-06-02 16:29 UTC, fp-mt approved these changes

2021-06-02 16:29 UTC, merged